export const PROFILE_SERVICE = Symbol("PROFILE_SERVICE")
export const PHOTOGRAPHERS_REPOSITORY = Symbol("PHOTOGRAPHERS_REPOSITORY")

export const PROPOSAL_SERVICE = Symbol("PROPOSAL_SERVICE")
export const PROPOSAL_REPOSITORY = Symbol("PROPOSAL_REPOSITORY")

export const COURSE_SERVICE = Symbol("COURSE_SERVICE")
export const COURSE_REPOSITORY = Symbol("COURSE_REPOSITORY")

export const LESSON_REPOSITORY = Symbol("LESSON_REPOSITORY")

export const COMPLETED_LESSONS_REPOSITORY = Symbol("COMPLETED_LESSONS_REPOSITORY")

export const BOUGHT_REPOSITORY = Symbol("BOUGHT_REPOSITORY")